name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT_TOKEN }}

      - name: Setup Git
        run: |
          git config --global user.email "agriyain2k@gmail.com"
          git config --global user.name "GitHub Actions Bot"

      - name: Deploy
        run: |
          git checkout -b gh-pages
          git add .
          git commit -m "Deploying to gh-pages"
          git push -f origin gh-pages
