name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Zola
        run: |
          curl -LO https://github.com/getzola/zola/releases/download/v0.19.2/zola-v0.19.2-x86_64-unknown-linux-gnu.tar.gz
          tar -xzf zola-v0.19.2-x86_64-unknown-linux-gnu.tar.gz
          sudo mv zola /usr/local/bin/
          rm zola-v0.19.2-x86_64-unknown-linux-gnu.tar.gz

      - name: Build with Zola
        run: zola build

      - name: Deploy to GitHub Pages
        run: |
          git config --global user.email "agriyain2k@gmail.com"
          git config --global user.name "lifeisacanvas24"
          git checkout -b gh-pages
          git add public/*
          git commit -m "Deploying to gh-pages"
          git push --force origin gh-pages
